_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 74
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 74
                - 103
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
arch:
    value: FPN
batch_size:
    value: 64
encoder:
    value: resnet34
epochs:
    value: 10
lr:
    value: 0.0002
